validate-deployment-settings: Added spack-config check, added comments

diff --git a/.github/actions/validate-deployment-settings/action.yml b/.github/actions/validate-deployment-settings/action.yml
--- a/.github/actions/validate-deployment-settings/action.yml
+++ b/.github/actions/validate-deployment-settings/action.yml
@@ -21,6 +21,9 @@ outputs:
 runs:
   using: composite
   steps:
+    ################
+    # SPACK CHECKS #
+    ################
     - name: Check All Spack Major Versions in Prerelease are in Release
       id: spack-maj-all-pre-in-rel
       shell: bash
@@ -93,6 +96,31 @@ runs:
           echo "msg=$msg" >> $GITHUB_OUTPUT
         fi
 
+        rm -rf ${{ env.CHECKOUT_DIR }}
+
+    #######################
+    # SPACK-CONFIG CHECKS #
+    #######################
+    - name: Verify spack-config Tag Exists
+      id: spack-config-tag-exists
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+        CHECKOUT_DIR: ./spack-config-metadata
+      run: |
+        gh repo clone access-nri/spack-config ${{ env.CHECKOUT_DIR }} -- --no-checkout --bare --filter=blob:none
+
+        if ! git -C ${{ env.CHECKOUT_DIR }} tag -l $spack_config_tag; then
+          msg="Tag $spack_config_tag does not exist in access-nri/spack-config"
+          echo "::${{ inputs.error-level }}::$msg"
+          echo "msg=$msg" >> $GITHUB_OUTPUT
+        fi
+
+        rm -rf ${{ env.CHECKOUT_DIR }}
+
+    #######################
+    # END OF ACTION STEPS #
+    #######################
     - name: Warning/Error Collector
       id: collector
       shell: bash
