Allow `@latest` (#235)
* get-spack-root-spec action: Allow `@latest` as ref

* cd.yml: Add a check so that a `@latest` version is not deployed as a Release

* deploy-1-setup.yml: Check that `@latest` isn't used in a non-draft PR

* get-spack-root-spec action: Move regex into it's own variable

* Update group regex to be appropriately quoted

diff --git a/.github/workflows/deploy-1-setup.yml b/.github/workflows/deploy-1-setup.yml
--- a/.github/workflows/deploy-1-setup.yml
+++ b/.github/workflows/deploy-1-setup.yml
@@ -183,6 +183,16 @@ jobs:
         id: current
         uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v4
 
+      - name: Check '@latest' version usage
+        if: >-
+          (github.event_name == 'pull_request' && !github.event.pull_request.draft) || 
+          (github.event_name == 'issue_comment' && !github.event.issue.draft)
+        run: |
+          if [[ "${{ steps.current.outputs.root-spec-ref }}" == "latest" ]]; then
+              echo "::error::The '@latest' version string is not allowed in non-draft PRs. It is reserved for a spack package that moves often and cannot be used as a future release tag"
+              exit 1
+          fi
+
       - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
         if: inputs.deployment-type != 'Release'
         continue-on-error: true
