Comment out strict checks, change refs to v5-model-tools

diff --git a/.github/workflows/deploy-1-setup.yml b/.github/workflows/deploy-1-setup.yml
--- a/.github/workflows/deploy-1-setup.yml
+++ b/.github/workflows/deploy-1-setup.yml
@@ -150,14 +150,14 @@ jobs:
 
       - name: Validate spack-packages version
         id: spack-packages
-        uses: access-nri/build-cd/.github/actions/validate-repo-version@v5
+        uses: access-nri/build-cd/.github/actions/validate-repo-version@v5-model-tools
         with:
           repo-to-check: spack-packages
           pr: ${{ inputs.deployment-ref }}
 
       - name: Validate spack version
         id: spack
-        uses: access-nri/build-cd/.github/actions/validate-repo-version@v5
+        uses: access-nri/build-cd/.github/actions/validate-repo-version@v5-model-tools
         with:
           repo-to-check: spack
           pr: ${{ inputs.deployment-ref }}
@@ -188,7 +188,7 @@ jobs:
 
       - name: Validate build-cd config/settings.json
         id: settings
-        uses: access-nri/build-cd/.github/actions/validate-deployment-settings@v5
+        uses: access-nri/build-cd/.github/actions/validate-deployment-settings@v5-model-tools
         with:
           settings-path: ./cd/config/settings.json
           target: ${{ inputs.deployment-target }}
@@ -213,143 +213,142 @@ jobs:
           fetch-depth: 0
           ref: ${{ inputs.deployment-ref }}
 
-      - name: Validate ACCESS-NRI spack manifest restrictions
-        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
-        uses: access-nri/schema/.github/actions/validate-with-schema@main
-        with:
-          schema-version: ${{ vars.SPACK_YAML_SCHEMA_VERSION }}
-          schema-location: au.org.access-nri/model/spack/environment/deployment
-          data-location: ${{ inputs.spack-manifest-path }}
+      # - name: Validate ACCESS-NRI spack.yaml Restrictions
+      #   if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
+      #   uses: access-nri/schema/.github/actions/validate-with-schema@main
+      #   with:
+      #     schema-version: ${{ vars.SPACK_YAML_SCHEMA_VERSION }}
+      #     schema-location: au.org.access-nri/model/spack/environment/deployment
+      #     data-location: ${{ inputs.spack-manifest-path }}
 
       - name: Get current (${{ inputs.deployment-ref }}) root spec version
         id: current
-        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v5
+        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v5-model-tools
         with:
           spack-manifest-path: ${{ inputs.spack-manifest-path }}
 
-      - name: Check root spec usage
-        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
-        run: |
-          if [[ "${{ steps.current.outputs.root-spec-ref }}" == "latest" ]]; then
-              echo "::error::The '@latest' version string is not allowed in non-draft PRs. It is reserved for a spack package that moves often and cannot be used as a future release tag"
-              exit 1
-          fi
+      # - name: Check root spec usage
+      #   if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
+      #   run: |
+      #     if [[ "${{ steps.current.outputs.root-spec-ref }}" == "latest" ]]; then
+      #         echo "::error::The '@latest' version string is not allowed in non-draft PRs. It is reserved for a spack package that moves often and cannot be used as a future release tag"
+      #         exit 1
+      #     fi
 
-          if [[ "${{ inputs.expected-root-spec-name }}" != "${{ steps.current.outputs.root-spec-name }}" ]]; then
-              echo "::error::The root spec in the spack manifest (${{ steps.current.outputs.root-spec-name }}) cannot be different from the expected root spec (${{ inputs.expected-root-spec-name }}) in non-Draft PRs."
-              exit 1
-          fi
+      #     if [[ "${{ inputs.expected-root-spec-name }}" != "${{ steps.current.outputs.root-spec-name }}" ]]; then
+      #         echo "::error::The root spec in the spack manifest (${{ steps.current.outputs.root-spec-name }}) cannot be different from the expected root spec (${{ inputs.expected-root-spec-name }}) in non-Draft PRs."
+      #         exit 1
+      #     fi
 
-      - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
-        if: inputs.deployment-type != 'Release'
-        continue-on-error: true
-        id: checkout-base-spack
-        run: |
-          git checkout ${{ inputs.prerelease-compare-ref }}
+      # - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
+      #   if: inputs.deployment-type != 'Release'
+      #   continue-on-error: true
+      #   id: checkout-base-spack
+      #   run: |
+      #     git checkout ${{ inputs.prerelease-compare-ref }}
 
-          if [ ! -f ${{ inputs.spack-manifest-path }} ]; then
-              echo "::notice::There is no previous version of ${{ inputs.spack-manifest-path }} to check at ${{ inputs.prerelease-compare-ref }}, continuing..."
-              exit 1
-          fi
+      #     if [ ! -f ${{ inputs.spack-manifest-path }} ]; then
+      #         echo "::notice::There is no previous version of ${{ inputs.spack-manifest-path }} to check at ${{ inputs.prerelease-compare-ref }}, continuing..."
+      #         exit 1
+      #     fi
 
-          # If the first commit in the repository is the template, there won't be anything defined in the speclist
-          # So we should skip checking the version!
-          if ! yq --exit-status '.spack.specs' ${{ inputs.spack-manifest-path }}; then
-            echo "::notice::${{ inputs.spack-manifest-path }} at ${{ inputs.prerelease-compare-ref }} is a template, continuing..."
-            exit 1
-          fi
+      #     # If the first commit in the repository is the template, there won't be anything defined in the speclist
+      #     # So we should skip checking the version!
+      #     if ! yq --exit-status '.spack.specs' ${{ inputs.spack-manifest-path }}; then
+      #       echo "::notice::${{ inputs.spack-manifest-path }} at ${{ inputs.prerelease-compare-ref }} is a template, continuing..."
+      #       exit 1
+      #     fi
 
-      - name: Get base root spec version
-        id: base
-        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure'
-        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v5
-        with:
-          spack-manifest-path: ${{ inputs.spack-manifest-path }}
+      # - name: Get base root spec version
+      #   id: base
+      #   if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure'
+      #   uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v5-model-tools
+      #   with:
+      #     spack-manifest-path: ${{ inputs.spack-manifest-path }}
 
-      - name: Check Model Version Modified
-        # We don't want to fire off model deployment version checks if the PR is never going to be merged.
-        # We determine this by checking if either the pull request, or the pull request that a comment
-        # belongs to, is drafted.
-        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure' && env.IS_NOT_DRAFT == 'true'
-        id: version-modified
-        run: |
-          if [[ "${{ steps.base.outputs.root-spec-ref }}" == "${{ steps.current.outputs.root-spec-ref }}" ]]; then
-              echo "::warning::The version string in ${{ inputs.spack-manifest-path }} hasn't been modified in this PR, but needs to be before merging."
-              exit 1
-          fi
+      # - name: Check Model Version Modified
+      #   # We don't want to fire off model deployment version checks if the PR is never going to be merged.
+      #   # We determine this by checking if either the pull request, or the pull request that a comment
+      #   # belongs to, is drafted.
+      #   if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure' && env.IS_NOT_DRAFT == 'true'
+      #   id: version-modified
+      #   run: |
+      #     if [[ "${{ steps.base.outputs.root-spec-ref }}" == "${{ steps.current.outputs.root-spec-ref }}" ]]; then
+      #         echo "::warning::The version string in ${{ inputs.spack-manifest-path }} hasn't been modified in this PR, but needs to be before merging."
+      #         exit 1
+      #     fi
 
-      - name: Same Model Version Failure Notifier
-        if: failure() && steps.version-modified.outcome == 'failure'
-        # TODO: We don't yet support bumping files outside of ./spack.yaml, so this is a temporary solution.
-        env:
-          BUMP_COMMENT_BODY: |-
-            Alternatively, comment the following to have it updated and committed automatically:
-              * `!bump major` for feature releases
-              * `!bump minor` for bugfixes
-        uses: access-nri/actions/.github/actions/pr-comment@main
-        with:
-          comment: |
-              The model version in the `${{ inputs.spack-manifest-path }}` has not been updated.
-              You can update it manually.
-              ${{ inputs.spack-manifest-path != './spack.yaml' && env.BUMP_COMMENT_BODY || '' }}
+      # - name: Same Model Version Failure Notifier
+      #   if: failure() && steps.version-modified.outcome == 'failure'
+      #   # TODO: We don't yet support bumping files outside of ./spack.yaml, so this is a temporary solution.
+      #   env:
+      #     BUMP_COMMENT_BODY: |-
+      #       Alternatively, comment the following to have it updated and committed automatically:
+      #         * `!bump major` for feature releases
+      #         * `!bump minor` for bugfixes
+      #   uses: access-nri/actions/.github/actions/pr-comment@main
+      #   with:
+      #     comment: |
+      #         The model version in the `${{ inputs.spack-manifest-path }}` has not been updated.
+      #         You can update it manually.
+      #         ${{ inputs.spack-manifest-path != './spack.yaml' && env.BUMP_COMMENT_BODY || '' }}
 
+      # - name: Check Projections - Specs
+      #   # This step checks that the root spec has an appropriate projection in the spack.yaml file.
+      #   id: projection-check-spec
+      #   continue-on-error: true
+      #   run: |
+      #     git checkout ${{ inputs.deployment-ref }}
 
-      - name: Check Projections - Specs
-        # This step checks that the root spec has an appropriate projection in the manifest file.
-        id: projection-check-spec
-        continue-on-error: true
-        run: |
-          git checkout ${{ inputs.deployment-ref }}
+      #     current_projection=$(yq '.spack.modules.default.tcl.projections.${{ steps.current.outputs.root-spec-name }}' ${{ inputs.spack-manifest-path }})
+      #     expected_projection_prefix='{name}/${{ steps.current.outputs.root-spec-ref }}'
 
-          current_projection=$(yq '.spack.modules.default.tcl.projections.${{ steps.current.outputs.root-spec-name }}' ${{ inputs.spack-manifest-path }})
-          expected_projection_prefix='{name}/${{ steps.current.outputs.root-spec-ref }}'
+      #     if [[ "$current_projection" == "$expected_projection_prefix"* ]]; then
+      #         echo "${{ inputs.spack-manifest-path }}: Current root spec projection ($current_projection) and expected projection prefix ($expected_projection_prefix) match."
+      #     else
+      #         echo "::error::${{ inputs.spack-manifest-path }}: Current root spec projection ($current_projection) and expected projection prefix ($expected_projection_prefix) don't match."
+      #         exit 1
+      #     fi
 
-          if [[ "$current_projection" == "$expected_projection_prefix"* ]]; then
-              echo "${{ inputs.spack-manifest-path }}: Current root spec projection ($current_projection) and expected projection prefix ($expected_projection_prefix) match."
-          else
-              echo "::error::${{ inputs.spack-manifest-path }}: Current root spec projection ($current_projection) and expected projection prefix ($expected_projection_prefix) don't match."
-              exit 1
-          fi
+      # - name: Check Projections - Packages
+      #   # This step checks that the defined projections have the same versions as the referenced packages in the spack.yaml file.
+      #   # For example, mom5@git.2023.12.12 matches with the
+      #   #  modulefile mom5/2023.12.12 (specifically, the version strings match)
+      #   id: projection-check-packages
+      #   continue-on-error: true
+      #   if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
+      #   run: |
+      #     FAILED="false"
+      #     # Get all the defined projections (minus 'all' and the root spec) and make them suitable for a bash for loop
+      #     DEPS=$(yq '.spack.modules.default.tcl.projections | del(.all) | del(.${{ steps.current.outputs.root-spec-name }}) | keys | join(" ")' ${{ inputs.spack-manifest-path }})
 
-      - name: Check Projections - Packages
-        # This step checks that the defined projections have the same versions as the referenced packages in the spack.yaml file.
-        # For example, mom5@git.2023.12.12 matches with the
-        #  modulefile mom5/2023.12.12 (specifically, the version strings match)
-        id: projection-check-packages
-        continue-on-error: true
-        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
-        run: |
-          FAILED="false"
-          # Get all the defined projections (minus 'all' and the root spec) and make them suitable for a bash for loop
-          DEPS=$(yq '.spack.modules.default.tcl.projections | del(.all) | del(.${{ steps.current.outputs.root-spec-name }}) | keys | join(" ")' ${{ inputs.spack-manifest-path }})
+      #     # for each of the module names
+      #     for DEP in $DEPS; do
+      #       # Capture the section after '@git.' or '@' (if it's not a git-attributed version) and before a possible '=' for a given dependency.
+      #       # Ex. '@git.2024.02.11' -> '2024.02.11', '@access-esm1.5' -> 'access-esm1.5', '@git.2024.05.21=access-esm1.5' -> '2024.05.21'
+      #       package_ver=$(yq ".spack.packages.\"$DEP\".require[0] | match(\"^@(?:git.)?([^=]*)\").captures[0].string" ${{ inputs.spack-manifest-path }})
+      #       expected_projection_prefix="{name}/$package_ver"
 
-          # for each of the module names
-          for DEP in $DEPS; do
-            # Capture the section after '@git.' or '@' (if it's not a git-attributed version) and before a possible '=' for a given dependency.
-            # Ex. '@git.2024.02.11' -> '2024.02.11', '@access-esm1.5' -> 'access-esm1.5', '@git.2024.05.21=access-esm1.5' -> '2024.05.21'
-            package_ver=$(yq ".spack.packages.\"$DEP\".require[0] | match(\"^@(?:git.)?([^=]*)\").captures[0].string" ${{ inputs.spack-manifest-path }})
-            expected_projection_prefix="{name}/$package_ver"
+      #       # Projections must start with '{name}/VERSION'. For example, '{name}/2024.11.11', or '{name}/2024.11.11-{hash:7}'
+      #       current_projection=$(yq ".spack.modules.default.tcl.projections.\"$DEP\"" ${{ inputs.spack-manifest-path }})
 
-            # Projections must start with '{name}/VERSION'. For example, '{name}/2024.11.11', or '{name}/2024.11.11-{hash:7}'
-            current_projection=$(yq ".spack.modules.default.tcl.projections.\"$DEP\"" ${{ inputs.spack-manifest-path }})
+      #       if [[ "$current_projection" == "$expected_projection_prefix"* ]]; then
+      #         echo "$DEP in ${{ inputs.spack-manifest-path }}: Current projection ($current_projection) and expected projection prefix ($expected_projection_prefix) match."
+      #       else
+      #         echo "::error::$DEP in ${{ inputs.spack-manifest-path }}: Current projection ($current_projection) and expected projection prefix ($expected_projection_prefix) don't match."
+      #         FAILED='true'
+      #       fi
+      #     done
+      #     if [[ "$FAILED" == "true" ]]; then
+      #       exit 1
+      #     fi
 
-            if [[ "$current_projection" == "$expected_projection_prefix"* ]]; then
-              echo "$DEP in ${{ inputs.spack-manifest-path }}: Current projection ($current_projection) and expected projection prefix ($expected_projection_prefix) match."
-            else
-              echo "::error::$DEP in ${{ inputs.spack-manifest-path }}: Current projection ($current_projection) and expected projection prefix ($expected_projection_prefix) don't match."
-              FAILED='true'
-            fi
-          done
-          if [[ "$FAILED" == "true" ]]; then
-            exit 1
-          fi
-
-      - name: Check Projections - Error Notifier
-        # If either of the Check Projection steps failed earlier, exit here
-        if: steps.projection-check-spec.outcome == 'failure' || steps.projection-check-packages.outcome == 'failure'
-        run: |
-          echo "::error::Some projections in ${{ inputs.spack-manifest-path }} don't match."
-          exit 1
+      # - name: Check Projections - Error Notifier
+      #   # If either of the Check Projection steps failed earlier, exit here
+      #   if: steps.projection-check-spec.outcome == 'failure' || steps.projection-check-packages.outcome == 'failure'
+      #   run: |
+      #     echo "::error::Some projections in ${{ inputs.spack-manifest-path }} don't match."
+      #     exit 1
 
       - name: Set Spack Env Name String
         id: get-env-name
@@ -361,7 +360,7 @@ jobs:
     needs:
       - check-config  # Verify configuration information is correct
       - check-spack-yaml  # Verify spack manifest information is correct
-    uses: access-nri/build-cd/.github/workflows/deploy-2-start.yml@v5
+    uses: access-nri/build-cd/.github/workflows/deploy-2-start.yml@v5-model-tools
     with:
       ref: ${{ inputs.deployment-ref }}
       version: ${{ inputs.deployment-version }}
