Run both projection checks despite failure, run package projections on push (CD)

diff --git a/.github/workflows/deploy-1-setup.yml b/.github/workflows/deploy-1-setup.yml
--- a/.github/workflows/deploy-1-setup.yml
+++ b/.github/workflows/deploy-1-setup.yml
@@ -246,6 +246,8 @@ jobs:
 
       - name: Check Projections - Specs
         # This step checks that the root spec has an appropriate projection in the spack.yaml file.
+        id: projection-check-spec
+        continue-on-error: true
         run: |
           git checkout ${{ inputs.deployment-ref }}
 
@@ -263,7 +265,10 @@ jobs:
         # This step checks that the defined projections have the same versions as the referenced packages in the spack.yaml file.
         # For example, mom5@git.2023.12.12 matches with the
         #  modulefile mom5/2023.12.12 (specifically, the version strings match)
+        id: projection-check-packages
+        continue-on-error: true
         if: >-
+          (github.event_name == 'push') ||
           (github.event_name == 'pull_request' && !github.event.pull_request.draft) ||
           (github.event_name == 'issue_comment' && !github.event.issue.draft)
         run: |
@@ -291,6 +296,13 @@ jobs:
           if [[ "$FAILED" == "true" ]]; then
             exit 1
           fi
+
+      - name: Check Projections - Error Notifier
+        # If either of the Check Projection steps failed earlier, exit here
+        if: steps.projection-check-spec.outcome == 'failure' || steps.projection-check-packages.outcome == 'failure'
+        run: |
+          echo "::error::Some projections in the spack manifest don't match."
+          exit 1
 
       - name: Set Spack Env Name String
         id: get-env-name
