Spack V1 Migration Feature:  Reserved Spack Definitions (#332)
* Rename action from get-spack-root-spec to get-spack-manifest, return only deployment-[name|version]

* cd.yml: Use get-spack-manifest, rework job names

* ci-comment.yml: Use get-spack-manifest, simplify update and commit of the bump

* deploy-1-setup.yml: Use get-spack-manifest, remove check on root spec usage

* deploy-2-start.yml: Remove unused manifest information

* fix: Add manifest path to action

* Update modules.py, prerelease.py to use reserved defs _name and _version

* Update tests

* Make reserved definitions flow-style for module injection too

* Remove references to RootSpecs, use ReservedDefinitions.get("name"), remove --keep-root-spec-intact flag

* Update pkg_repo_url logic to use spack.repo.PATH.get_pkg_class()

* getter.py fixes from code review
Update reserved defs getter return value, remove case statement, revert autoformatter

* Update test input manifest formatting

* Add back manifest info step

* Update pre/release injections to handle multiple specs, simplify custom release projection logic

* Change release injection --packages from space-sep to comma-sep, as convention

* Update tests

* Explicitly disallow multi-spec Releases

* get-spack-manifest: call the getter.py script

* Import yaml representers from own class

* Small fixes

diff --git a/.github/workflows/deploy-1-setup.yml b/.github/workflows/deploy-1-setup.yml
--- a/.github/workflows/deploy-1-setup.yml
+++ b/.github/workflows/deploy-1-setup.yml
@@ -279,7 +279,7 @@ jobs:
       pull-requests: write
     outputs:
       # Release version of the deployment. Inferred if not given in inputs.deployment-version
-      release: ${{ steps.current.outputs.root-spec-ref }}
+      release: ${{ steps.current.outputs.deployment-version }}
       # Spack env name in form <model>-<version>
       spack-env-name: ${{ steps.get-env-name.outputs.env-name }}
     steps:
@@ -298,21 +298,19 @@ jobs:
 
       - name: Get current (${{ inputs.deployment-ref }}) root spec version
         id: current
-        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v8
+        uses: access-nri/build-cd/.github/actions/get-spack-manifest@v8
         with:
           spack-manifest-path: ${{ inputs.spack-manifest-path }}
 
-      - name: Check root spec usage
-        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
+      - name: Disallow multi-spec Releases
+        if: inputs.deployment-type == 'Release'
+        # FIXME: Once the necessary infrastructure/guidance is in place, remove this step. See ACCESS-NRI/build-cd#344
         run: |
-          if [[ "${{ steps.current.outputs.root-spec-ref }}" == "latest" ]]; then
-              echo "::error::The '@latest' version string is not allowed in non-draft PRs. It is reserved for a spack package that moves often and cannot be used as a future release tag"
-              exit 1
-          fi
+          root_specs=$(yq '.spack.specs | select(.[] == "${{ steps.current.outputs.deployment-name }}*") | length' ${{ inputs.spack-manifest-path }})
 
-          if [[ "${{ inputs.expected-root-spec-name }}" != "${{ steps.current.outputs.root-spec-name }}" ]]; then
-              echo "::error::The root spec in the spack manifest (${{ steps.current.outputs.root-spec-name }}) cannot be different from the expected root spec (${{ inputs.expected-root-spec-name }}) in non-Draft PRs."
-              exit 1
+          if [ "$root_specs" -gt 1 ]; then
+            echo "::error::We don't yet support multiple root specs with the same package name. Contact the Model Release Team for information."
+            exit 1
           fi
 
       - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
@@ -337,7 +335,7 @@ jobs:
       - name: Get base root spec version
         id: base
         if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure'
-        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v8
+        uses: access-nri/build-cd/.github/actions/get-spack-manifest@v8
         with:
           spack-manifest-path: ${{ inputs.spack-manifest-path }}
 
@@ -348,7 +346,7 @@ jobs:
         if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure' && env.IS_NOT_DRAFT == 'true'
         id: version-modified
         run: |
-          if [[ "${{ steps.base.outputs.root-spec-ref }}" == "${{ steps.current.outputs.root-spec-ref }}" ]]; then
+          if [[ "${{ steps.base.outputs.deployment-version }}" == "${{ steps.current.outputs.deployment-version }}" ]]; then
               echo "::warning::The version string in ${{ inputs.spack-manifest-path }} hasn't been modified in this PR, but needs to be before merging."
               exit 1
           fi
